### ISSUE TITLE
Allow default-site to be specified during CIFS server creation

### ISSUE THREAD

**Issue by dilsonn** [ansible-collections/netapp.ontap#101]
### Summary

When creating a CIFS server via the command line, we have the default-site option available. This option isn't available when using na_ontap_cifs_server, can we get this added?

### Component Name

na_ontap_cifs_server

### Additional Information

This would allow us to specify a default site during CIFS server creation.

**Comment by carchi8py** [comment]
The ONTAP team has added this option in to the REST API with ONTAP 9.13.1

we have story DEVOPS-6331 open for this.

**Comment by carchi8py** [comment]
This was fixed in 22.8.0
