### ISSUE TITLE
Removing qtree with NTFS security style fails

### ISSUE THREAD

**Issue by AdrianBronder** [ansible-collections/netapp.ontap#106]
**Issue Summary**:
- Removing qtree with NTFS security style and no unix_permissions set will fail with REST

**Link to Code**:
https://github.com/ansible-collections/netapp.ontap/blob/60fad9cc11e1c67f9ed5497f40143b1270911206/plugins/modules/na_ontap_qtree.py#L270

**Full error message**:
localhost | FAILED! => {
    "changed": false,
    "module_stderr": "/home/badrian/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1050: InsecureRequestWarning: Unverified HTTPS request is being made to host '<ip_hidden>'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\n/home/badrian/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1050: InsecureRequestWarning: Unverified HTTPS request is being made to host '<ip_hidden>'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/home/badrian/.ansible/tmp/ansible-tmp-1663666939.5591471-8880-257559971910691/AnsiballZ_na_ontap_qtree.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/badrian/.ansible/tmp/ansible-tmp-1663666939.5591471-8880-257559971910691/AnsiballZ_na_ontap_qtree.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/badrian/.ansible/tmp/ansible-tmp-1663666939.5591471-8880-257559971910691/AnsiballZ_na_ontap_qtree.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netapp.ontap.na_ontap_qtree_payload_czm5g6ve/ansible_netapp.ontap.na_ontap_qtree_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_qtree.py\", line 474, in <module>\n  File \"/tmp/ansible_netapp.ontap.na_ontap_qtree_payload_czm5g6ve/ansible_netapp.ontap.na_ontap_qtree_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_qtree.py\", line 470, in main\n  File \"/tmp/ansible_netapp.ontap.na_ontap_qtree_payload_czm5g6ve/ansible_netapp.ontap.na_ontap_qtree_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_qtree.py\", line 431, in apply\n  File \"/tmp/ansible_netapp.ontap.na_ontap_qtree_payload_czm5g6ve/ansible_netapp.ontap.na_ontap_qtree_payload.zip/ansible_collections/netapp/ontap/plugins/modules/na_ontap_qtree.py\", line 270, in get_qtree\nKeyError: 'unix_permissions'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Environment**
- ONTAP 9.9.1P9
- python 3.6.8
- Ansible Core 2.11.10 (issue appears on other versions as well)
- netapp.ontap collection: 21.23.0

**Create Task**
- name: Create qtree
  netapp.ontap.na_ontap_qtree:
    <<: *login
    state: present
    flexvol_name: <vol_name>
    name: <qtree_name>
    security_style: ntfs
    vserver: <vserver_name>
    use_rest: never

**Delete Task**
- name: Delete qtree
  netapp.ontap.na_ontap_qtree:
    <<: *login
    state: absent
    name: <qtree_name>
    flexvol_name: <vol_name>
    vserver: <vserver_name>

**Workaround**
- Setting "use_rest" to "never"

**Additional Info**
- works without issues for UNIX security style qtrees with UNIX permissions set

**Comment by lonico** [comment]
DEVOPS-5485

**Comment by carchi8py** [comment]
This was fixed in 21.24.0.
