### ISSUE TITLE
Unable to set the administrative status of physical ports

### ISSUE THREAD

**Issue by chjones45** [ansible-collections/netapp.ontap#11]
##### SUMMARY
Unable to set the administrative status of physical ports. This is the equivalent of the "net port modify -up-admin" CLI command that takes a true or false value.

##### ISSUE TYPE
Inability to control the administrative state of physical ports on controllers in an ONTAP Cluster.

##### COMPONENT NAME
na_ontap_net_port

##### ADDITIONAL INFORMATION
In ONTAP physical ports that are in the "up-admin true" state but have no cable connected generate an alert in System Manager as being offline.

At the Advanced privilege level of the CLI the "network port modify -node <node> -port <port> -up-admin false" command administratively shuts down physical ports so they do no generate alerts about being disconnected.

I would hope an attribute such as "administrative_state" could be added to the na_ontap_net_port module to support administratively disabling unused data ports.

This has long been a concern of ONTAP customers, that unused ports in the system would generate alerts for having no cable connected. The ONTAP developers have finally resolved this in the past 18 months by having System Manager check the up-admin state of a port. If a physical port is "up-admin false" then customers do not get alerted about a port having no connection.

**Comment by lonico** [comment]
fixed in 21.8.0
