### ISSUE TITLE
Bad examples on na_ontap_aggregate

### ISSUE THREAD

**Issue by ansibleguy76** [ansible-collections/netapp.ontap#117]
### Summary

I am trying the example on the ansible site and many have an example with disk-count.  But with disk-count the property "nodes" is required.  What is already silly, because in the comments of this property you already claim that "node (single)" is required.  So the examples are wrong (missing nodes) but the comment is somehow also wrong as it talks about "node".

### Component Name

na_ontap_aggregate

### Additional Information

```yaml (paste below)

```

**Comment by lonico** [comment]
The examples were written for ZAPI.  We need to update them.
I don't understand the last part I see
```
With REST, nodes is required if disk_count is present.
```

DEVOPS-5666

**Comment by carchi8py** [comment]
This was fixed in 22.1.0 which was released last week.
