### ISSUE TITLE
EMS event notifications and filters

### ISSUE THREAD

**Issue by bryanheo** [ansible-collections/netapp.ontap#122]
### Summary

Hello

I have deployed many NetApp CVOs and all the volumes are managed by ansible-collections/netapp.ontap.
I can see netapp.ontap.na_ontap_ems_destination module but I cannot find any modules regarding EMS event notifications and filters. I need to repeatedly create many filters. Could you let me know whether the features are available?  If not, could you let me know when the features are available?

https://docs.netapp.com/us-en/ontap-automation/manage/ems-rest-api.html#ontap-rest-api-versus-ontap-cli-commands

Regards
Moon

### Component Name

EMS event notifications and filters

### Additional Information

```yaml (paste below)

```

**Comment by lonico** [comment]
The GET APIs are supported in na_ontap_rest_info.

We don't have anything to create filters or add filter rules.  

We already have a request for this that is tracked with DEVOPS-5381, but we don't have a plan yet.

**Comment by carchi8py** [comment]
THis was complete as part of 22.4.0
