### ISSUE TITLE
Documentation update for deprecated Modules

### ISSUE THREAD

**Issue by ReneMeier** [ansible-collections/netapp.ontap#126]
### Summary

Update the documentation that these Modules only support ZAPI

    • na_ontap_cg_snapshot
    • na_ontap_file_directory_policy
    • na_ontap_svm_options
    • na_ontap_quota_policy

Mentioned from Chris in the Ansible Collection 21.24.0 announcement on Discord, that these Modules have been deprecated. These modules do not have REST equivalent API's. 

### Component Name

Multiple Modules. See in Summary

### Additional Information

See example in Module na_ontap_active_directory in the section NOTES
- Only supported with ZAPI.

**Comment by lonico** [comment]
This is documented in https://github.com/ansible-collections/netapp.ontap/wiki/Rest_Support

But yes, we should have this in each module as well.

DEVOPS-5734
