### ISSUE TITLE
Unknown CA error however CA is installed and valid on the cluster

### ISSUE THREAD

**Issue by edd1619** [ansible-collections/netapp.ontap#128]
Hello,

We are receiving the following error running a playbook, however the CA is confirmed installed and valid on the cluster.

NetApp API failed. Reason - URL error:URLError(SSLError(1, '[SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1131)'))"

Any help to why this error occurs with valid cert?

Thanks! 

Also to note, the PEM/KEY files have been confirmed as accurate in the project, and is synced with AWX.

**Comment by lonico** [comment]
These issues are better discussed on Discord: https://discord.gg/netapp

Could you try to run the following playbook with -vvv and provide the output
https://github.com/ansible-collections/netapp.ontap/blob/main/playbooks/examples/support/debug_connectivity.yaml

You could run first as is, and a second time with validate_certs set to true.

**Comment by edd1619** [comment]
Thanks. We cannot access Discord, blocked by company policy, however this issue is due to certificate chain issues which we are in process of fixing.
