### ISSUE TITLE
Review Examples in Module: netapp.ontap.na_ontap_file_security_permissions module

### ISSUE THREAD

**Issue by ReneMeier** [ansible-collections/netapp.ontap#134]
### Summary

Please review the examples in the Module netapp.ontap.na_ontap_file_security_permissions module. None of these examples are working due to missing parameters and make even sense.

### Component Name

na_ontap_file_security_permissions

### Additional Information

```yaml (paste below)

```

**Comment by carchi8py** [comment]
We have Story DEVOPS-5908 open for this.

**Comment by carchi8py** [comment]
This was updated in 22.4.0
