### ISSUE TITLE
na_ontap_user_role defaulting to REST when using ZAPI parameters

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp.ontap#137]
### Summary

I am using na_ontap_user_role to create/modify roles. My playbook fails with collection version 22.3.0 on second execution.

### Component Name

na_ontap_user_role

### Ansible Version

```console
$ ansible --version
ansible [core 2.13.7]
  config file = /home/user/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.0.3
  libyaml = True
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
Collection   Version
------------ -------
netapp.ontap 22.3.0
```

### ONTAP Version

```console
NetApp Release 9.10.1P10: Sun Dec 18 16:24:34 UTC 2022
```

### Playbook

```console
- hosts: localhost
  become: false
  gather_facts: false
  connection: local
  collections:
    - netapp.ontap
  name: ONTAP Debug
  vars:
    login: &login
      hostname: "clustername"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: true
  tasks:
  - name: test user role
    na_ontap_user_role:
      state: present
      vserver: "clustername"
      name: operator
      command_directory_name: "network interface migrate"
      access_level: all
      <<: *login
```

### Steps to Reproduce

```yaml (paste below)

```
Execute example playbook. Setting "use_rest: never" works as a workaround.

### Expected Results

Successful run of the playbook

### Actual Results

```console
First run works, but subsequent runs fail.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
failed: [clustername] (item=Role: operator; Command: DEFAULT; Access: readonly) => {"ansible_loop_var": "item", "changed": false, "item": [{"name": "operator", "role_access": [{"access": "readonly", "cmd": "DEFAULT"}, {"access": "all", "cmd": "network interface migrate"}, {"access": "all", "cmd": "network interface modify"}, {"access": "all", "cmd": "network interface revert"}, {"access": "all", "cmd": "security login password"}, {"access": "all", "cmd": "security login role show-user-capability"}, {"access": "readonly", "cmd": "security login show"}, {"access": "all", "cmd": "security login whoami"}, {"access": "all", "cmd": "set"}, {"access": "all", "cmd": "snapmirror"}, {"access": "all", "cmd": "system health alert delete"}, {"access": "all", "cmd": "volume autosize"}, {"access": "all", "cmd": "volume efficiency"}, {"access": "all", "cmd": "volume explore"}, {"access": "all", "cmd": "volume modify"}, {"access": "all", "cmd": "volume move"}, {"access": "all", "cmd": "volume qtree"}, {"access": "all", "cmd": "volume quota"}, {"access": "all", "cmd": "volume size"}, {"access": "all", "cmd": "volume snapshot"}, {"access": "all", "cmd": "vserver cifs share"}, {"access": "all", "cmd": "vserver locks"}, {"access": "all", "cmd": "vserver services access-check"}, {"access": "all", "cmd": "vserver export-policy"}]}, {"access": "readonly", "cmd": "DEFAULT"}], "msg": "Error creating role operator: calling: security/roles: got {'message': 'Role already exists in legacy role table.', 'code': '5636171'}."}
```

**Comment by mohanrajb9** [comment]
The error is expected one- 'Role already exists in legacy role table.'
we cannot add REST API privilege to a role that has already created with legacy command/command directory paths.

from [REST doc](https://library.netapp.com/ecmdocs/ECMLP2882307/html/index.html#/) DOC /security/roles.

A role can comprise of multiple privilege tuples and each privilege tuple consists of a REST API or command/command directory path, its access level, and an optional query. For a given role, only one type of privilege tuple can be defined. All privilege tuples for a role must contain REST API paths or all privilege tuples for the role must contain command/command directory paths. However, predefined/built-in roles (those defined later) are an exception to this rule.


```
    - name: Create cluster user role with legacy commands.
      na_ontap_user_role:
        state: present
        command_directory_name: "network interface migrate"
        access_level: all
        name: role1
        <<: *login910
    
    - name: Create cluster user role with legacy commands - idempotent check.
      na_ontap_user_role:
        state: present
        command_directory_name: "network interface migrate"
        access_level: all
        name: role1
        <<: *login910
    
    - name: Try to add REST API path to role that has legacy commands.
      na_ontap_user_role:
        state: present
        privileges:
          - path: /api/cluster/jobs
        name: role1
        <<: *login910
        
TASK [Create cluster user role with legacy commands.] ***************************************************************************************
changed: [localhost]

TASK [Create cluster user role with legacy commands - idempotent check.] ********************************************************************
ok: [localhost]

TASK [Try to add REST API path to role that has legacy commands.] ***************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating role privilege /api/cluster/jobs: calling: security/roles/05056b34578/role1/privileges: got {'message': 'Role already exists in legacy role table.', 'code': '5636171'}."}
```

we can improve the error message.

**Comment by mamoep** [comment]
But I only used the example I pasted in the description.

**Comment by mohanrajb9** [comment]
I cannot reproduce the issue with both node and data vservers, maybe I am missing something.
delete the role and enable tracing in the task you have posted in the original post as explained in 
https://github.com/ansible-collections/netapp.ontap/wiki/Debugging 
and share the logs generated in /tmp/ontap_apis.log  to carchi@netapp.com and mohan.raj2@netapp.com.?

**Comment by mamoep** [comment]
I sent the log as requested.

**Comment by mamoep** [comment]
In further tests I found out the following:
- ZAPI creates roles similar to command "security login role create"
- REST creates roles similar to command "security login rest-role create"
- Roles with the same name cannot exist as role and rest-role at the same time in ONTAP. 

I think there is still some bug in the module. There are examples for na_ontap_user_role using REST and using ZAPI. But when I specify the parameters ZAPI-style it defaults to REST and fails with the following error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [clustername]: FAILED! => {"changed": false, "msg": "Error creating role privilege network interface migrate: calling: security/roles/b4c2859a-a158-11ed-8600-0050568c7d5a/operator_rest/privileges: got {'message': 'Specified URI path is invalid or not supported. Verify that the URI contains only valid characters.', 'code': '5636169'}."}
```

**Comment by mohanrajb9** [comment]
REST supports both command(ZAPI style) and REST(api/storage/volume) privileges when creating roles but not both at same role.
[DOC
 [/security/roles]](https://library.netapp.com/ecmdocs/ECMLP2882307/html/index.html#/docs/security/security_roles).


> In further tests I found out the following:
> 
> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
> fatal: [clustername]: FAILED! => {"changed": false, "msg": "Error creating role privilege network interface migrate: calling: security/roles/b4c2859a-a158-11ed-8600-0050568c7d5a/operator_rest/privileges: got {'message': 'Specified URI path is invalid or not supported. Verify that the URI contains only valid characters.', 'code': '5636169'}."}
> ```

from this error, I can say there is a role already exist, REST tries to add command/api to the role, but the error is coming from the ONTAP, you might get similar error if you try it cli also.

**Comment by mamoep** [comment]
Shouldn't the module check if the role already exists?

**Comment by mohanrajb9** [comment]
yes module finds the role exists good. 
A role can have multiple commands or API privileges.
the command you were trying to add does not exist in the role, so the module tries to add it to role and ONTAP throws error back.

 adding role name to module error might help a little.
`"Error creating role privilege"   --> "Error creating role privilege in rest_role". if rest_role is the role name`

**Comment by mamoep** [comment]
I tried to delete the role and run the playbook again but the issue remains. No matter how you turn it, this module is buggy!

**Comment by carchi8py** [comment]
For the module the `use_rest` variable if it is going to use REST or ZAPI, by default it will use REST
https://docs.ansible.com/ansible/devel/collections/netapp/ontap/na_ontap_user_role_module.html#parameter-use_rest

On the Rest side the module will call the REST API /security/roles https://library.netapp.com/ecmdocs/ECMLP2884821/html/index.html#/security/role_collection_get

**Comment by mohanrajb9** [comment]
@mamoep 
with 22.4.0 release, we restricted not to use command/command directory path in REST for ONTAP < 9.11.1, set use_rest: never if need to add command/command directory path to a role.

from 9.11.1 REST API can get both role and rest-role, but we cannot add command path to rest-role and rest api path to role.

**Comment by mamoep** [comment]
Thanks a lot for this change!
