### ISSUE TITLE
Efficiency policy info

### ISSUE THREAD

**Issue by kbreit-insight** [ansible-collections/netapp.ontap#138]
### Summary

I would like to have the `ontap_info` module provide information on all efficiency policies that are configured on the system.

### Component Name

ontap_info

### Additional Information

```yaml (paste below)

```

**Comment by carchi8py** [comment]
You should be able to do this with the `na_ontap_rest_info` module with the `storage/volume-efficiency-policies` subset 
https://docs.ansible.com/ansible/devel/collections/netapp/ontap/na_ontap_rest_info_module.html#ansible-collections-netapp-ontap-na-ontap-rest-info-module
