### ISSUE TITLE
Retry after configuration baseline lock

### ISSUE THREAD

**Issue by robertattenberger** [ansible-collections/netapp.ontap#147]
### Summary

In some circumstances a module-call returns with the following error message:
"This Vserver is temporarily locked from changes while recording the configuration baseline. Try again in a few minutes or manually stop configuration replication by running \"vserver config-replication pause\" and retry the command.', 'code': '2621573', 'target': 'security_style"

This error occurs occasionally when some configuration changes with multiple module-calls are made in a sort time.

To avoid the problem at the moment I place a pause-task (about 10 seconds) in the playbook at the position where it occurs.

It would be great if the ontap-modules would not fail, but do a retry themself after a couple of seconds, if it gets that response from the Ontap-REST-API.

### Component Name

ontap.netapp.*

### Additional Information

The problem occors at IP-Metroclusters.

Here are some sequences, where the error occurs. The last task is each the failing one:
- create new SVM -> create efficiency policies in the new SVM -> create servicepolicies in the new SVM ->create LIFs in the new SVM -> create routes in the new SVM
- create new volume -> set snapdir-access with REST-CLI to the new volume -> set autosize-settings to the new volume
- create new qtree -> set quota for the new qtree
- create new volume -> set autosize-settings to the new volume -> set snapdir-access and atime-update with REST-CLI to the new volume

**Comment by mohanrajb9** [comment]
we are looking in to this.

can you add debug to tasks which throws error
```
feature_flags:
        trace_apis: true
```
 and mail us the logs saved in /tmp/ontap_apis.log.
 more info on - https://github.com/ansible-collections/netapp.ontap/wiki/Debugging

**Comment by robertattenberger** [comment]
May you please provide me a mail-address to send you the logs.

**Comment by mohanrajb9** [comment]
sorry, I missed it in my post this one - ng-ansibleteam@netapp.com

**Comment by mohanrajb9** [comment]
Thanks @robertattenberger for sharing the logs, tracked internally with DEVOPS-6192.
can you please share the baseline configuration lock error message you are getting on volume and quota module here.

**Comment by mamoep** [comment]
Same problem as issue #47

**Comment by carchi8py** [comment]
This was fixed in 22.6.0
