### ISSUE TITLE
SVM tunneling with `na_ontap_rest_info`

### ISSUE THREAD

**Issue by tacerus** [ansible-collections/netapp.ontap#162]
### Summary

Hi,

currently only [na_ontap_restit module](https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_restit_module.html#ansible-collections-netapp-ontap-na-ontap-restit-module) seems to allow a Vserver to be specified.
Is there a way to do this with the [na_ontap_rest_info module](https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_rest_info_module.html#ansible-collections-netapp-ontap-na-ontap-rest-info-module)? If not, could it be taken as a feature request?

My use case is allowing the query of volume/LUN details with a REST API user only available on a specific Vserver. The `rest_info` module is much simpler to use for such queries.

### Component Name

na_ontap_rest_info

### Additional Information

n/a

**Comment by carchi8py** [comment]
with the rest_info module
https://library.netapp.com/ecmdocs/ECMLP2885799/html/index.html#/storage/volume_collection_get

you should be able to set any of the parameters listed on that page using the parameters option.
https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_rest_info_module.html#parameter-parameters

so you should be able to set this up exactly like the API call you would do outside of ansble.
