### ISSUE TITLE
Retry after configuration baseline lock

### ISSUE THREAD

**Issue by robertattenberger** [ansible-collections/netapp.ontap#164]
### Summary

In the Github-Issue #147 the error according the Vserver-Lock because of recording a configuration baseline was solved for some modules. But in at least the module netapp.ontap.na_ontap_cifs_local_group_member the error still occurs. It would be fine if the problem could also be solved in the other modules.

The collection version we are using is at the moment 22.6.0. As far as I can see from the changelog, never version do not have changes to this subject.

### Component Name

netapp.ontap.*

### Additional Information

See Issue #147

**Comment by carchi8py** [comment]
I'm looking in to this. The fix we made should of been global at our REST CALL level but let me check whats going on here.

**Comment by mamoep** [comment]
Adding reference to BURT 1525926

fixed in:
9.14.1RC1
9.13.1P1
9.12.1P5
9.11.1P11
9.10.1P14
9.9.1P17
