### ISSUE TITLE
na_ontap_info module metrocluster aggr_efficiency_info error

### ISSUE THREAD

**Issue by jnp31** [ansible-collections/netapp.ontap#18]
na_ontap_info module returns error when using the aggr_efficiency_info option against a metrocluster system. it seems to be trying to gather information about aggregate on partner system. all other options work fine for a metrocluster system.

"msg": "Error: key 'node' not found for aggr-efficiency-get-iter, got: {'aggregate': 'partnersystem_aggr'}"

**Comment by jnp31** [comment]
Thanks. I was able to use continue on error with key_error switch as a workaround to the issue.

**Comment by lonico** [comment]
fixed by f5973d81e0e26b5aa9041015ba82971eaf651135
will be released as 21.15.0.
