### ISSUE TITLE
typos in na_ontap_info

### ISSUE THREAD

**Issue by ansibleguy76** [ansible-collections/netapp.ontap#188]
### Summary

property: use_rest => This module only support ZAPI and will can not be swtich to REST

Multiple typos, should be "This module only support**s** ZAPI and **cannot** **switch** to REST

this poor english makes us look incompetent.  

### Component Name

na_ontap_info

### Ansible Version

```console
$ ansible --version
N/A
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
N/A
```

### ONTAP Version

```console
sridharc-vsim34::> version
NetApp Release 9.7.0: Tue May 18 10:45:16 UTC 2021
N/A
```

### Playbook

```console
N/A
```

### Steps to Reproduce

N/A

### Expected Results

N/A

### Actual Results

```console
N/A
```

**Comment by carchi8py** [comment]
We will have a fix for this in the next release.

**Comment by spencer-cdw** [comment]
This typo is still showing up in the latest documentation

https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_info_module.html#ansible-collections-netapp-ontap-na-ontap-info-module
