### ISSUE TITLE
na_ontap_cifs_server - support for multichannel and max-connections

### ISSUE THREAD

**Issue by DoktorByte** [ansible-collections/netapp.ontap#200]
### Summary

I would like to be able to set the two options is-multichannel-enabled and max-connections-per-session when creating the CIFS server.

I would do this on the CLI as follows:
vserver cifs options modify -vserver svm01  -is-multichannel-enabled true -max-connections-per-session 4

### Component Name

na_ontap_cifs_server

### Additional Information

```yaml (paste below)

```

**Comment by carchi8py** [comment]
We won't be able to add max-connections-per-session as that not supported by the REST API 
https://docs.netapp.com/us-en/ontap-restmap-9141/cifs.html#cifs-options-get-iter

is-multichannel-enabled can be added and i have story DEVOPS-6680 open for this.

**Comment by suhasbshekar** [comment]
This is released in 22.10.0, will be closing this issue.
