### ISSUE TITLE
na_ontap_cifs - add support for offline_files property

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp.ontap#201]
### Summary

I am using na_ontap_cifs to create CIFS shares. The property `offline_files` is currently not supported by the module and should be added. It was added to the REST API in 9.10.1

### Component Name

na_ontap_cifs

### Additional Information

n/a

**Comment by carchi8py** [comment]
I have story 6715

**Comment by suhasbshekar** [comment]
this is released in 22.11.0, will be closing this issue.

**Comment by mamoep** [comment]
I can see no 22.11.0. When will it be released?

**Comment by suhasbshekar** [comment]
Will be releasing by next week.
