### ISSUE TITLE
na_ontap_rest_info fails also with ignore_api_error

### ISSUE THREAD

**Issue by tanganellilore** [ansible-collections/netapp.ontap#221]
### Summary

Hi team,

I tested today the `na_ontap_rest_info` module with `gather_subset: all` on different ontap version 9.13.

I receive the following error:

`Failed to queue the \"metrocluster check\" job in cluster *********. Reason: MetroCluster is not supported when HAOSC is not set to \"mcc\", \"mcc-2n\" or \"mccip\". Run the \"ha-config modify chassis\" and \"ha-config modify controller\" commands in maintenance mode to change the HAOSC settings on node \"*******\" in cluster \"*****\". Retry the operation. If the error persists, contact technical support for assistance."`

I tried to set `ignore_api_error` to ` metrocluster` or `is not supported` but not works.

I think that the error is related to this piece of code:
https://github.com/ansible-collections/netapp.ontap/blob/42d01558a8558fa19ad47ee5a0517fc24774218f/plugins/modules/na_ontap_rest_info.py#L548-L562

I think that error is not a dict so module return directly the message, ignoring completly the `ignore_api_error` params.

I tried also to set zapi, but is not supporte on ontap 9.13

  

### Component Name

na_ontap_rest_info

### Ansible Version

```console
2.15.12
```

### ONTAP Collection Version

```console
- name: netapp.ontap
  version: 22.12.0
```

### ONTAP Version

```console
NetApp Release 9.13.1P8
```

### Playbook

```console
- name: Get ONTAP info
      netapp.ontap.na_ontap_rest_info:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        https: true
        validate_certs: false
        gather_subset:
          - all
        ignore_api_errors:
          - "is not supported"
      register: ontap_info
```

### Steps to Reproduce

Run the module on a netapp that don't have metrocluster

### Expected Results

 `ignore_api_error` will skip the error and continue with other api call

### Actual Results

```console
`Failed to queue the \"metrocluster check\" job in cluster *********. Reason: MetroCluster is not supported when HAOSC is not set to \"mcc\", \"mcc-2n\" or \"mccip\". Run the \"ha-config modify chassis\" and \"ha-config modify controller\" commands in maintenance mode to change the HAOSC settings on node \"*******\" in cluster \"*****\". Retry the operation. If the error persists, contact technical support for assistance."`
```

**Comment by carchi8py** [comment]
@tanganellilore We highly highly do not recommend using 
`gather_subset: all` 

We don't even have this option listed in the documentation anymore (https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_rest_info_module.html#parameter-gather_subset) 

I think we still have an example with it that we should remove.

The reason you shouldn't use ALL. Is this will call every single ONTAP get Rest API (100's of apis), and return HUGE amount of data. 

You should be only calling the specific get function that has the data your looking for. Something like this

`- name: run ONTAP gather facts for volume info with query on name and state
  netapp.ontap.na_ontap_rest_info:
      hostname: "1.2.3.4"
      username: "testuser"
      password: "test-password"
      https: true
      validate_certs: false
      gather_subset:
        - storage/volumes
      parameters:
        name: ansible*
        state: online`
        
  I'll add a story though to remove the all example from the documentation.

**Comment by tanganellilore** [comment]
:+1
