### ISSUE TITLE
Could we install the Slack Github app for the netapp.* projects

### ISSUE THREAD

**Issue by carchi8py** [ansible-collections/netapp.ontap#3]
@gundalow wasn't sure the best way to reach you, so making an issue in our collection. Would it be possible to install the slack github app (https://slack.github.com/) in to ansible-collection org? We use slack for everything and would like to receive notifications in slack from GitHub when there is issues/pull requests.

**Comment by gundalow** [comment]
@gundalow Hi Chris. I've enabled Slack for all (current & future) repos under ansible-collection org.

Could you please test and let me if it works/

**Comment by carchi8py** [comment]
Yep it worked thanks
