### ISSUE TITLE
onboard key manager support

### ISSUE THREAD

**Issue by Jiawei0227** [ansible-collections/netapp.ontap#30]
### Summary

I am trying to setup onboard key manager using ansible but could not find an ansible module can do the work.

It seems like the existing ONTAP REST API does support onboard key manager setup. So it would be nice if we could extend na_ontap_security_key_manager to include this capability.

### Component Name

na_ontap_security_key_manager

### Additional Information

```yaml (paste below)

```

**Comment by carchi8py** [comment]
We have added an internal story DEVOPS-4867 for this issue.

**Comment by carchi8py** [comment]
This has been fixed with the 21.23.0 release.
