### ISSUE TITLE
add start stop to na_ontap_svm

### ISSUE THREAD

**Issue by christian-naenny** [ansible-collections/netapp.ontap#37]
It would be very helpful if it was possible to start/stop SVMs via the na_ontap_svm module.
What about extending the state with the options started and stopped. Or maybe add another parameter admin_state with the possible values of started and stopped? If I have to start and stop SVMs with the na_ontap_command module the whole indempotency is a bit tricky...

**Comment by lonico** [comment]
fixed by d1139b116665f477542d79ef99e87e9a079c6558
will be released as 21.15.0
