### ISSUE TITLE
Create Snaplock Volumes on ONTAP 9.10.1 and later

### ISSUE THREAD

**Issue by Posti90** [ansible-collections/netapp.ontap#51]
### Summary

After updating to Ontap 9.10.1 we are unable to create Snaplock Volumes with ansible. In this release Snaplock is set on the Volume level, not Aggregate level. If you want to use Snaplock you must provide “-snaplock-type non-snaplock/compliance/enterprise” parameter on Volume creation.
Module netapp.ontap.na_ontap_volume does not support the snaplock parameter Please consider bringing back Snaplock Support.

Documentation for Snaplock with ONTAP 9.10.1:
https://docs.netapp.com/us-en/ontap/snaplock/create-snaplock-aggregate-task.html

### Component Name

netapp.ontap.na_ontap_volume

### Additional Information

```yaml (paste below)

```

**Comment by lonico** [comment]
We also have a na_ontap_volume_snaplock module, but it would not help in this case as the type needs to be set at volume creation.

So the best option is to add this to na_ontap_volume.

**Comment by lonico** [comment]
fixed in 21.18.0
