### ISSUE TITLE
Duplicate snapmirror

### ISSUE THREAD

**Issue by bryanheo** [ansible-collections/netapp.ontap#57]
### Summary

Hello

I am creating snapmirror for FlexGroups but Cloud Manager shows the duplicate snapmirrors as shown below
Please see the code below

`
    - name: Create ONTAP/ONTAP SnapMirror
      na_ontap_snapmirror:
        state: present
        source_endpoint:
          path: "{{ vserver }}:{{ item.key }}"
        destination_endpoint:
          path: "{{ dr_vserver }}:{{ item.key }}_copy"
        schedule: hourly
        policy: MirrorAllSnapshots
        initialize: True
        hostname: "{{ dr_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
      with_dict: "{{ volumes }}" 
`

![Screenshot 2022-04-02 at 14 23 08](https://user-images.githubusercontent.com/12592663/161385314-2a9ad031-8f73-4b73-8637-cdf0d2e01df9.png)

### Component Name

SnapMirror

### Ansible Version

```console
$ ansible --version
2.11.2
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
Collection          Version
------------------- -------
community.general   3.3.2  
netapp.cloudmanager 21.15.0
netapp.ontap        21.17.3
```

### ONTAP Version

```console
netappprimary::> version
NetApp Release 9.10.1: Sat Jan 15 15:04:44 UTC 2022
```

### Playbook

```console
- name: create flexgroup
      na_ontap_volume:
        state: present
        name: "{{ item.key }}"
        is_infinite: False
        size: "{{ item.value.size }}"
        size_unit: "{{ item.value.size_unit }}"
        tiering_policy: all
        space_guarantee: none
        aggr_list: "aggr1"
        aggr_list_multiplier: 1
        vserver: "{{ vserver }}"
        wait_for_completion: True
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false            
      with_dict: "{{ volumes }}"

    - name: create flexgroup (DR)
      na_ontap_volume:
        state: present
        name: "{{ item.key }}_copy"
        is_infinite: False
        size: "{{ item.value.size }}"
        size_unit: "{{ item.value.size_unit }}"
        tiering_policy: all
        type: dp
        aggr_list: "aggr1"
        aggr_list_multiplier: 1        
        vserver: "{{ dr_vserver }}"
        wait_for_completion: True
        hostname: "{{ dr_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false            
      with_dict: "{{ volumes }}"


    - name: Create cluster peer
      netapp.ontap.na_ontap_cluster_peer:
        state: present
        source_intercluster_lifs: "{{ intercluster }}"
        dest_intercluster_lifs: "{{ dr_intercluster }}"
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        peer_options:
          hostname: "{{ dr_hostname }}"
        encryption_protocol_proposed: tls_psk
        https: true
        validate_certs: false           


    - name: Source vserver peer create
      netapp.ontap.na_ontap_vserver_peer:
        state: present
        peer_vserver: "{{ vserver }}"
        peer_cluster: "{{ cluster }}"
        vserver: "{{ dr_vserver }}"
        applications: ['snapmirror']
        hostname: "{{ dr_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dest_hostname: "{{ hostname }}"
        https: true
        validate_certs: false
      register: vserver_peer            

    - name: accept vserver peer
      na_ontap_command:
        command: ['vserver', 'peer', 'accept', '-vserver', '{{ dr_vserver }}', '-peer-vserver', '{{ vserver }}']
        privilege: 'advanced'
        return_dict: true
        hostname: "{{ dr_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
      with_items: "{{ volumes }}"
      when: vserver_peer.changed

    - name: Create ONTAP/ONTAP SnapMirror
      na_ontap_snapmirror:
        state: present
        source_endpoint:
          path: "{{ vserver }}:{{ item.key }}"
        destination_endpoint:
          path: "{{ dr_vserver }}:{{ item.key }}_copy"
        schedule: hourly
        policy: MirrorAllSnapshots
        initialize: True
        hostname: "{{ dr_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
      with_dict: "{{ volumes }}"
```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

Only one SnapMirror needs to appear on Cloud Manager

### Actual Results

```console
Duplicate SnapMirror on Cloud Manager with <volume>__0001 suffix
```

**Comment by bryanheo** [comment]
Please see the volume variables below

`
"volumes":
  "data1":
    "client_ips":
    - "x.x.x.x/12"
    - "x.x.x.x/12"
    "protocols":
    - "nfs3"
    - "nfs4"
    "size": "500"
    "size_unit": "gb"
  "data2":
    "client_ips":
    - "x.x.x.x/12"
    - "x.x.x.x/12"
    "protocols":
    - "nfs3"
    - "nfs4"
    "size": "500"
    "size_unit": "gb"
`

**Comment by carchi8py** [comment]
@bryanheo volumes is only a single volume?

**Comment by bryanheo** [comment]
I tested single volume and multiple volumes, and the both of them shows duplicate SnapMirror
Single volume SnapMirror: 

- modelstore -> modelstore_copy and modelstore__0001 -> modelstore_copy__0001

Multiple volume SnapMirror: 

- data1 -> data1_copy and data1__0001 -> data1_copy__0001
- data2 -> data2_copy and data2__0001 -> data2_copy__0001

**Comment by carchi8py** [comment]
Could you run the playbook with a new volume with -vvv and send out the full output. You can mail it to ng-ansibleteam@netapp.com

It doesn't look like it being caused by our module (it may be the ONTAP it self), but to rule that out if you could send the output from ansible-playbook with -vvv that should help us rule out the module.

**Comment by bryanheo** [comment]
As you mentioned, Cloud Manager shows the duplicate SnapMirrors by Ansible collection and CLI so I have created NetApp support ticket (2009131910)

**Comment by bryanheo** [comment]
According to NetApp support team, FlexGroups are not supported on the Cloud Manager and Replication panel as well.
So NetApp support team has confirmed that we can ignore the issue for now.
Thank you for your support
