### ISSUE TITLE
Allow na_ontap_volume module to set the filesys_size_fixed attribute

### ISSUE THREAD

**Issue by db0** [ansible-collections/netapp.ontap#6]
##### SUMMARY

When a volume's `filesys_size_fixed` attribute is set to true, it prevent the volume from being resized with the following error

```
fatal: [server]: FAILED! => {"changed": false, "msg": "Error re-sizing volume ansible_data_nfstst: NetApp API failed. Reason - 160:Unable to set volume attribute \"size\" for volume \"ansible_data_nfstst\" on Vserver \"ansible-tst01\". Reason: Volume has the fixed filesystem size option set. "}
```

This property can be seen using `na_ontap_info` module under the following key:

```
na_ontap_info_volume_info.ontap_info.volume_info[VOLUME + ':' + VSERVER].volume_space_attributes.is_filesys_size_fixed 
```

The solution to this issue is to set this attribute to false. Using the CLI, the command would be thus

```
volume modify -volume volume_name -vserver vserver_name -filesys-size-fixed false
```

I want the possibility to do likewise using ansible.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

na_ontap_volume 

##### ADDITIONAL INFORMATION

This small attribute can block all resizing automation  on a volume. Having the option to set it via ansible will ensure it's not a problem

**Comment by lonico** [comment]
According to https://library.netapp.com/ecmdocs/ECMLP2874886/html/zapi_to_rest_table.html
this parameter is not supported in REST.
I'll share this issue with ONTAP product team to bring this to their awareness.

**Comment by Evyatar-Gefen** [comment]
Using the library for ontap 9.9.1and it seems that this has not been added.
Since this issue is closed I assume this has been added at some point. It would be great to know from which version this is supportes.
If it has not been added, I would like to request for this issue to be reopened.
This option is very important.
