### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by mpichlba** [ansible-collections/netapp.ontap#65]
https://github.com/ansible-collections/netapp.ontap/blob/1258c7b3dab5d58a73daebb8fe8108f403a1b009/plugins/modules/na_ontap_command.py#L96

typo in command module example: 
![image](https://user-images.githubusercontent.com/86420007/165137231-ae9fe95c-c96f-4311-a288-245e8915dc70.png)

**Comment by carchi8py** [comment]
@lonico can you add the Jira story that this change is coming in to the story (just to make tracking a little easier)

**Comment by lonico** [comment]
fixed by b8c4933f1470d6703978e176eba5df6d69f74661

**Comment by lonico** [comment]
published in 21.19.0
