### ISSUE TITLE
Add support for adding users with SAML as the authentication method

### ISSUE THREAD

**Issue by richardnaik** [ansible-collections/netapp.ontap#70]
### Summary

I would like to be able to add users and set the SAML authentication method for them. Currently we have SAML auth working through our IDP on our Netapp appliance but since we have to add users locally on the appliance before they can authenticate with our IDP this is rather cumbersome. Automating with this ansible would be perfect but SAML is not a supported authentication method through the user module.

### Component Name

netapp.ontap.na_ontap_user

### Additional Information

- name: create admin users
  netapp.ontap.na_ontap_user:
    state: present
    name: "{{ item }}"
    applications: http,ontapi
    authentication_method: saml
    role_name: admin
    vserver:
    hostname: "{{ netapp_hosts[0] }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  loop: "{{ admin_users }}"
  
  Would like to be able to set the authentication method as above. I can do this through the ONTAP UI or the CLI.

**Comment by carchi8py** [comment]
I've created story 5090 for this.

**Comment by lonico** [comment]
published as 21.20.0

**Comment by richardnaik** [comment]
SAML now works as an auth method, thanks
