### ISSUE TITLE
Set logical space reporting and enforcement via na_ontap_volume Module

### ISSUE THREAD

**Issue by DoktorByte** [ansible-collections/netapp.ontap#8]
##### SUMMARY
We want to use the module "na_ontap_volume" to set the options for logical space reporting and enforcement

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
na_ontap_volume

##### ADDITIONAL INFORMATION
vol modify -vserver _SVM_ -volume _VOLUME_ -is-space-reporting-logical _True|False_
vol modify -vserver _SVM_ -volume _VOLUME_ -is-space-enforcement-logical _True|False_

**Comment by carchi8py** [comment]
@DoktorByte i have this change targeted to come out in the next release.

**Comment by carchi8py** [comment]
This was fixed in 21.16.0
