### ISSUE TITLE
netapp.ontap.na_ontap_info - lun_info: serial-hex

### ISSUE THREAD

**Issue by orb71** [ansible-collections/netapp.ontap#80]
### Summary

Hi! 
The module returns only the serial number, it would be useful to have access to the hex version. VMware community module requires the NAA and there is no straightforward way to convert the serial with Ansible.

Regards,
Oli

### Component Name

na_ontap_info

### Additional Information

```yaml (paste below)

```

**Comment by lonico** [comment]
We're doing it in na_ontap_lun_map, inside return_naa_id.  I agree it would be more useful in na_ontap_info or na_ontap_rest_info.

**Comment by lonico** [comment]
DEVOPS-5214

**Comment by lonico** [comment]
fixed in 21.21.0
