### ISSUE TITLE
does na_ontap_wait_for_condition module only work for sp-firmware-update like in the example?

### ISSUE THREAD

**Issue by toggit** [ansible-collections/netapp.ontap#83]
### Summary

Hello guys,

i have questions about using: na_ontap_wait_for_condition

i am trying to figure out if  i can use na_ontap_wait_for_condition to wait for snapmirror update to complete.

in the documentation 
i can only see example for sp_upgrade  but i have different use case.
does it only support predefine use cases?
where and how can i find all the predefine use cases?
does this module support custom use cases?  like waiting for snapmirror update job to finish?

### Component Name

na_ontap_wait_for_condition

### Additional Information

```yaml (paste below)

```

**Comment by lonico** [comment]
Yes, it currently supports only two conditions related to SP firmware update.

But as we are updating the module to support REST, we'll look if it's possible to support your use case (waiting for snapmirror to be idle),

**Comment by lonico** [comment]
DEVOPS-5263

**Comment by lonico** [comment]
fixed in 21.22.0
