### ISSUE TITLE
add space_reserve/space_allocation support with san template

### ISSUE THREAD

**Issue by orb71** [ansible-collections/netapp.ontap#85]
### Summary

Today, using the san template doesn't let you specify, ignore  space_reserve and space_allocation.  It would be a nice addition

### Component Name

na_ontap_lun

### Additional Information

```yaml (paste below)

```

**Comment by lonico** [comment]
This is currently not supported by the REST API.
But it's a problem, as SAN application default to space_reserve True.

We're looking into changing space_reserve after the creation or update.
But it's still a problem, as the initial creation requires all the space to be available.

**Comment by orb71** [comment]
Do you recommend doing all provisioning steps manually (volume, multiple luns) and staying away from the san template?

**Comment by lonico** [comment]
Sorry I missed this.
I think the value of using the application template is when you want a cookie cutter approach.  You sacrifice customization for simplicity.  If you need more control , I would recommend doing the provisioning manually.

**Comment by lonico** [comment]
Not supported by application template.
