### ISSUE TITLE
Add parameter "exclude_network_config" to na_ontap_snapmirror_policy module

### ISSUE THREAD

**Issue by jaiw23** [ansible-collections/netapp.ontap#86]
### Summary

Ontap allows creating snapmirror policy for SVM DR with the option "discard-network-config". The reason for this is when customers don't have a network config same on prod and DR, they can assign separate IPs subnet, etc for their PRD and DR SVM, still keeping other SVM configs same by using the identity-preserve flag as true.

It would be good to have this included in **na_ontap_snapmirror_policy** module !
 

### Component Name

na_ontap_snapmirror_policy

### Additional Information

```yaml (paste below)

```

**Comment by jaiw23** [comment]
@lonico I see the option on the Ontap Rest API doc page

![image](https://user-images.githubusercontent.com/53182616/182205773-2e90619d-fe23-42d4-9785-ed15a13fa1c9.png)

**Comment by rbenigno** [comment]
+1

**Comment by lonico** [comment]
Good point.  I'm not sure if it was added recently or the documentation I was looking at is incorrect.

DEVOPS-5409

**Comment by lonico** [comment]
fixed in 22.0.0
