### ISSUE TITLE
vserver cifs users-and-groups local-user create module is requested.

### ISSUE THREAD

**Issue by jhpark011** [ansible-collections/netapp.ontap#87]
### Summary

Hi Team,
We are field engineers that support NetApp.
I am inquiring at the customer's request.

**Is there a vserver cifs users-and-groups local-user create module in ansible?**

1. CLI-based Command:
cluster1::> vserver cifs users-and-groups local-user create -vserver [vs1.example.com](http://vs1.example.com/)  user-name SMB_SERVER01\sue
 
Enter the password:
Confirm the password:
 
cluster1::> vserver cifs users-and-groups local-user show
Vserver  User Name                  Full Name  Description
-------- -------------------------- ---------- -------------
vs1      SMB_SERVER01\Administrator            Built-in administrator account
vs1      SMB_SERVER01\sue            Sue Chang

https://docs.netapp.com/us-en/ontap-cli-97/vserver-cifs-users-and-groups-local-user-create.html#description

**I would like to ask you to confirm that vserver cifs users-and-groups local-user create is possible.**

- e-mail : parkjh@klic.co.kr

Thanks!

### Component Name

vserver cifs users-and-groups local-user create module

### Additional Information

**Is there a vserver cifs users-and-groups local-user create module in ansible?**

**Comment by carchi8py** [comment]
We have story 4762 open for this issue.

**Comment by carchi8py** [comment]
This update will be included in the 21.23.0 release
