### ISSUE TITLE
netapp.ontap/roles/na_ontap_cluster_config/ License Mismatch

### ISSUE THREAD

**Issue by bobshithers** [ansible-collections/netapp.ontap#88]
### Summary

The LICENSE file in netapp.ontap/roles/na_ontap_cluster_config/ has it listed as AGPL, where the README.md is GNU v3. All the other modules are GNU v3 as well.

### Component Name

LICENSE

### Ansible Version

```console
$ ansible --version
```

### ONTAP Collection Version

```console
$ ansible-galaxy collection list
```

### ONTAP Version

```console
sridharc-vsim34::> version
NetApp Release 9.7.0: Tue May 18 10:45:16 UTC 2021
```

### Playbook

```console
N/A
```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

LICENSE and README.md to be consistent

### Actual Results

```console
N/A
```

**Comment by carchi8py** [comment]
This looks like a mistake i'll update this soon.

**Comment by bobshithers** [comment]
@carchi8py any update on when this will be changed? The current AGPL license is a sticking point for our organization.
Thank you!

**Comment by carchi8py** [comment]
It will be updated with our 21.23.0 release on Wednesday (Sep 7)
