### ISSUE TITLE
Need rest-role related Ansible modules

### ISSUE THREAD

**Issue by alejandromlopez** [ansible-collections/netapp.ontap#93]
## Summary
There currently exists an Ansible module to create a role: https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_user_role_module.html

However, there doesn't exist one to create a rest-role. Currently, a potential workaround would be to use [na_ontap_command](https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_command_module.html), but this doesn't support cert-based authentication. 

## Component Name
na_ontap_user_rest_role

## Additional Information
There doesn't seem to be a way to use Ansible to create rest-roles on an SVM with cert-based authentication. This would have very similar use cases to na_ontap_user_role, especially since there also exists an Ansible module to create a [user](https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_user_module.html)

**Comment by carchi8py** [comment]
Hey guys, we are currently working on this for our next release, as part of our adding of REST support to this module.

**Comment by carchi8py** [comment]
This has been fixed with the 21.23.0 release.
